# Generated by Django 5.2.7 on 2026-01-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
