# Generated by Django 5.2.7 on 2025-10-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0003_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
