# Generated by Django 5.2.7 on 2025-11-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0005_employee_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
